name: Code and Documentation Analysis

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.js'
      - '**.ts'

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          output: ' '
      
      - name: Analyze code changes
        id: analyze_changes
        run: |
          node .github/workflows/analyze_changes.js '${{ steps.file_changes.outputs.files_added_modified }}'

      - name: Update documentation
        id: update_docs
        run: |
          node .github/workflows/update_docs.js '${{ steps.analyze_changes.outputs.json_changes }}'
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated README.md" -a
